# Site theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "wizzie"

# Site Settings
locale: "en-US"
title: 'ZZ-CEP'
title_separator: "-"
name: 'Wizzie Analytics'
baseurl: '/zz-cep'
description: 'ZZ-CEP is a complex engine processing based on Kafka and Siddhi'
repository: 'wizzie-io/zz-cep'

# Site search
search: true
search_provider: google
search_full_content: true

google:
    search_engine_id: 015992723382350682522:4u8h3rlqahc
    instant_search: true

google_site_verification: MjIfY0_y_7qIgMjaLFMggPJaLitLhygQ3eodF9Y5ITY

# Social Sharing
twitter:
    username: &twitter "wizzieio"
og_image: '/assets/images/logo.png'

defaults:
# _docs
- scope:
      path: ""
  values:
      toc_sticky: true
      sidebar:
          nav: "docs"

# Site Footer
footer:
    links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/wizzieio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wizzie-io"